// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBHdmWNfzUaZqnX0rx5ZAhIxK-UiuwZc1s",
      authDomain: "maintenance-1a1f3.firebaseapp.com",
      projectId: "maintenance-1a1f3",
      storageBucket: "maintenance-1a1f3.appspot.com",
      messagingSenderId: "1095461056610",
      appId: "1:1095461056610:web:6a8edfa6eec86bea3b613b",
      measurementId: "G-Y6L3WF87FT");

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdK0WnU1anJh1JPj42wJWCbtq18UZ83Cc',
    appId: '1:1095461056610:android:9437cd1098dccbfe3b613b',
    messagingSenderId: '1095461056610',
    projectId: 'maintenance-1a1f3',
    storageBucket: 'maintenance-1a1f3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAmFjuMBU3BJhpJYsd8xp3zPGbOZ_D62g',
    appId: '1:1095461056610:ios:52bfc243ece359393b613b',
    messagingSenderId: '1095461056610',
    projectId: 'maintenance-1a1f3',
    storageBucket: 'maintenance-1a1f3.appspot.com',
    iosClientId:
        '1095461056610-cuopfpri5bpfepcgfe480mg9lphm8qvt.apps.googleusercontent.com',
    iosBundleId: 'com.altamonteinc.mtto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAmFjuMBU3BJhpJYsd8xp3zPGbOZ_D62g',
    appId: '1:1095461056610:ios:52bfc243ece359393b613b',
    messagingSenderId: '1095461056610',
    projectId: 'maintenance-1a1f3',
    storageBucket: 'maintenance-1a1f3.appspot.com',
    iosClientId:
        '1095461056610-cuopfpri5bpfepcgfe480mg9lphm8qvt.apps.googleusercontent.com',
    iosBundleId: 'com.altamonteinc.mtto',
  );
}
